### ISSUE TITLE
Error in new account.payment.group when it has a "Memo" (communication)

### ISSUE THREAD

**Issue by sotolucas** [ingadhoc/account-payment#188]
**Error:**
```
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/custom/src/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 1324, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 1312, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/auto/addons/account_payment_group_document/models/account_payment_group.py", line 139, in post
    default_l10n_latam_document_type_id=rec.document_type_id.id)).post()
  File "/opt/odoo/auto/addons/account_payment_group/models/account_payment_group.py", line 539, in post
    rec.payment_ids.sorted(key=lambda l: l.signed_amount).filtered(lambda x: x.state == 'draft').post()
  File "/opt/odoo/auto/addons/account_check/models/account_payment.py", line 511, in post
    res = super(AccountPayment, self).post()
  File "/opt/odoo/auto/addons/account_withholding/models/account_payment.py", line 48, in post
    return super(AccountPayment, self).post()
  File "/opt/odoo/auto/addons/payment/models/account_payment.py", line 99, in post
    res = super(AccountPayment, self - payments_need_trans).post()
  File "/opt/odoo/auto/addons/account/models/account_payment.py", line 686, in post
    moves = AccountMove.create(rec._prepare_payment_moves())
  File "/opt/odoo/auto/addons/account_check/models/account_payment.py", line 515, in _prepare_payment_moves
    vals = super(AccountPayment, self)._prepare_payment_moves()
  File "/opt/odoo/auto/addons/account_withholding/models/account_payment.py", line 53, in _prepare_payment_moves
    move_vals = super(AccountPayment, rec)._prepare_payment_moves()
  File "/opt/odoo/auto/addons/account_payment_group/models/account_payment.py", line 341, in _prepare_payment_moves
    move_vals[0]['ref'] = "%s%s" % (self.payment_group_id.communication, move_vals['ref'] or '')
TypeError: list indices must be integers or slices, not str
```
Seems [this line](https://github.com/ingadhoc/account-payment/blob/4f2d8677b8fb6e38dedce3e543bda2d90fa48620/account_payment_group/models/account_payment.py#L341) is transforming index in a string.

**Comment by sotolucas** [comment]
@jjscarafia the change was made on 13.0 migration.
Would you check this out?

**Comment by jjscarafia** [comment]
Fixed on this commit https://github.com/ingadhoc/account-payment/commit/9e7eb60f887ae02c6cf615fc87389574ab831028
Thanks for reporting!
