### ISSUE TITLE
[11.0] Débito del Banco para cheque propio en pago a proveedores. Error.

### ISSUE THREAD

**Issue by sebatista** [ingadhoc/account-payment#192]
Hola, estamos utilizando éste módulo.
Realizamos una factura de proveedor. 
Luego un pago a proveedor correspondiente a la factura. 
Agregamos una línea de pago como la siguiente: 
![image](https://user-images.githubusercontent.com/27778036/79393349-8b072f00-7f4b-11ea-8b92-9ae87c5fdf45.png)
El inconveniente se presenta cuando utilizamos el botón "Débito del banco" 
en el módulo contabilidad -> Caja y Bancos -> Cheques propios.

El diario, del tipo Banco, tenía, como método de pago: Manual, Cheque propio y Cheques. 
Se modificó y se dejó tildado únicamente Cheque propio.

La traza nos arroja la siguiente información: 
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo-server/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo-server/odoo/api.py", line 699, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo-server/odoo/api.py", line 690, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/ADHOC/account-payment-11.0/account_check/wizard/account_check_action_wizard.py", line 33, in action_confirm
    check.with_context(action_date=self.date), self.action_type)()
  File "/opt/odoo/addons/ADHOC/account-payment-11.0/account_check/models/account_check.py", line 472, in bank_debit
    payment_values = self.get_payment_values(self.journal_id)
  File "/opt/odoo/addons/ADHOC/account-payment-11.0/account_check/models/account_check.py", line 631, in get_payment_values
    journal._default_outbound_payment_methods().id,
  File "/opt/odoo/odoo-server/odoo/fields.py", line 2577, in __get__
    raise ValueError("Expected singleton: %s" % record)
ValueError: Expected singleton: account.payment.method(2, 15)

**Comment by jjscarafia** [comment]
Buenas, lo que veo rápidamente es que nosotros dejamos la opción "manual". o sea, típicamente un diario de banco puede pagar realizando transferencias (manual) o con cheques (cheque propio).
Podrás revisar si con esa config te anda bien? Por alguna razón sacarón manual?

Igual ahí vi el problema, es porque tienen instalado "account_check_printing" y de alguna manera este módulo no es compatible con ese. Además que account_check_printing no le suma nada a account_check, o si?

**Comment by sebatista** [comment]
En principio gracias por responder.
Inicialmente estaban tildadas las 3 opciones de pago: Manual, Cheque propio y Cheques.
En base al error un programador en un grupo de Odoo, nos indico que puede deberse a que la función nos devuelve mas de una opción, entonces tira el error, que le dejemos una única opción.
Ése módulo no se utiliza, se instaló por si resultaba útil, pero entiendo que permite la impresión de cheques propios, lo cual NO es estrictamente necesario. 

Se desinstaló el módulo y funcionó correctamente el botón.
Agregó una línea en la opción de Contabilidad -> Cheques y Banco -> Cheques propios, en el cheque en cuestión, con el estado "Debitado".
Además, realizó los apuntes contables correspondientes en cheque y en banco.
No se si hay otra cosa que revisar?
Gracias por el reporte de incompatibildad conocida con otro módulo.

**Comment by jjscarafia** [comment]
Buenísimo @sebatista .
Si, para imprimir cheques usando el módulo "account_check" se hace de otra manera, sin ese módulo de odoo que está para la lógica de cheques de odoo (sin cheques endozados, ni a fecha ni demás).

Dentro de poco vamos a hacer algún meet para explicar mejor estas cuestiones.

Saludos!

**Comment by jjscarafia** [comment]
Cierro por inactividad
