### ISSUE TITLE
[16.0] account_cashbox Error en el control de cierre con diario en moneda distinta a la de la compania

### ISSUE THREAD

**Issue by juanpgarza** [ingadhoc/account-payment#366]
Esta dando error en el control de cierre cuando el diario es en moneda distinta a la de la compania.
Si no se informa el saldo real da un error:

Les dejo un video explicativo:

[https://youtu.be/sLk8o3ROOuE](url)

Les copio el error:
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/data/build/adhoc-cicd-odoo-odoo/odoo/http.py", line 1583, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/data/build/adhoc-cicd-odoo-odoo/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/data/build/adhoc-cicd-odoo-odoo/odoo/http.py", line 1610, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/data/build/adhoc-cicd-odoo-odoo/odoo/http.py", line 1807, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/data/build/adhoc-cicd-odoo-odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/data/build/adhoc-cicd-odoo-odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/data/build/adhoc-cicd-odoo-odoo/odoo/http.py", line 696, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/data/build/adhoc-cicd-odoo-odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/data/build/adhoc-cicd-odoo-odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/adhoc-cicd-odoo-odoo/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/data/build/adhoc-cicd-odoo-odoo/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/ingadhoc-account-payment/account_cashbox/models/account_cashbox_session.py", line 110, in action_account_cashbox_session_close
    self.write({'state': 'closed'})
  File "/data/build/adhoc-cicd-odoo-odoo/addons/mail/models/mail_thread.py", line 315, in write
    result = super(MailThread, self).write(values)
  File "/data/build/adhoc-cicd-odoo-odoo/addons/mail/models/mail_activity_mixin.py", line 241, in write
    return super(MailActivityMixin, self).write(vals)
  File "/data/build/adhoc-cicd-odoo-odoo/odoo/models.py", line 3759, in write
    real_recs._validate_fields(vals, inverse_fields)
  File "/data/build/adhoc-cicd-odoo-odoo/odoo/models.py", line 1348, in _validate_fields
    check(self)
  File "/data/build/ingadhoc-account-payment/account_cashbox/models/account_cashbox_session.py", line 121, in _check_pop_session_balance
    max_diff_in_currency = line.journal_id.currency_id._convert(
TypeError: Currency._convert() missing 2 required positional arguments: 'company' and 'date'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://11745-16-0-all.runbot.adhoc.com.ar/web/assets/1114-a841044/web.assets_backend.min.js:977:163)
    at XMLHttpRequest.<anonymous> (https://11745-16-0-all.runbot.adhoc.com.ar/web/assets/1114-a841044/web.assets_backend.min.js:985:13)

**Comment by juanpgarza** [comment]
@jjscarafia
